unknown_command: "未知的命令"
successful_reload: "重载成功"
negative_effects:
  - 'BLINDNESS'
  - 'CONFUSION'
  - 'DARKNESS'
  - 'HUNGER'
  - 'POISON'
  - 'SLOW'
  - 'SLOW_DIGGING'
  - 'UNLUCK'
  - 'WEAKNESS'
  - 'WITHER'
areas:
  'hotSpring':
    location:
      x1: -1499
      y1: 67
      z1: -3290
      x2: -1489
      y2: 56
      z2: -3300
    exp_points: 1
    is_in_water: true
    remove_all_negative_points: true
    effects:
      - 'REGENERATION'
      - 'WATER_BREATHING'