name: EffectOnBlock
version: '${version}'
main: net.toiletmc.effectonblock.EffectOnBlock
api-version: 1.19
authors: [ TheLittle_Yang ]
website: https://toiletmc.net
commands:
  effectonblock:
    aliases: eob
    permission: effectonblock.command.admin
permissions: { }